#!/bin/bash

set -e

if [ "$#" -ne 3 ]; then
    echo >&2 "Usage: $0 <source> <target> <device>"
    exit 1
fi

source="$1"
target="$2"
device="$3"

qemu-img create -f qcow2 -b "$source" -o compat=0.10 "$target" 20G

qemu-nbd --connect="$device" "$target"

trap "qemu-nbd --disconnect $device" EXIT

sleep 1

growpart "$device" 1

e2fsck -y -f "${device}p1"
resize2fs -f "${device}p1"
